Title: Assault Day
Alternate Titles: Test;Me
Library: arcade
Series: null
Developer: Matthew Jamieson
Publisher: mjgames-online.com; assaultday.com
Play Mode: Single Player
Release Date: 2009-08-29
Version: null
Languages: en
Extreme: No
Tags: Shooter; Action
Tag Categories: default; default
Source: http://mjgames-online.com/games/assault_day.php
Platform: Flash
Status: Playable
Application Path: FPSoftware\Flash\flashplayer_32_sa.exe
Launch Command: http://mjgames-online.com/swf/assaultday.swf
Game Notes: null
Original Description: "WASD keys for movement mouse for aiming and shooting "
Curation Notes: null
Additional Applications: {}
